---
title: "SProject Documentation"
author: "Adam, JD, Malachi"
date: "November 23, 2015"
output: html_document
---

In this project we used data about weather events in the US to create a crosstab, bar chart, and scatterplot.

Crosstab: The Crosstab uses a KPI of total damage over elapsed time to pinpoint where the most destructive events occurred and what type of event they were. The Adjustable Slider filters out data below a certain level to eliminate outlier or low data. The data is updated by clicking the "Generate Plot" Button.

Scatter Plot: The Scatter Plot is a combination of two different visuals that compare the crop damage and property damage of natural disasters that happened for less than 24 hours. The plot is designed to show the disasters that effect property and crops individually and compare these two. The duration of events was taken by mutating a column that calculated the absolute value of the difference between the start and end time for events that occured within one day.

Link to the Shiny App:
https://adamthemanrhino.shinyapps.io/DV_SProject_Shiny_App
